namespace Domain.Constans;
public static class AllowedSectors
{
    public static readonly HashSet<string> Names = new()
    {
        "AMPLIACION",
        "15 DE OCTUBRE",
        "18 DE FEBRERO",
        "6 DE DICIEMBRE",
        "A",
        "A1",
        "ADESESEP",
        "ASOCIACION COMERCIANTES",
        "B2",
        "B3",
        "B4",
        "CERRO CACHITO",
        "E",
        "E1",
        "E2",
        "E3",
        "E5",
        "E6",
        "JENNY BUMACHAR",
        "MARBAL",
        "MERCADO PESQUERO",
        "MERCADO UNIFICADOS",
        "MINIPARQUE INDUSTRIAL CERO CACHITO",
        "OASIS",
        "PARCELA I",
        "PARCELA MINI PARQUE INDUSTRIAL OASIS",
        "PESQUERO 3",
        "PESQUERO 4",
        "PROYECTO INTEGRAL",
        "PUERTO BAHIA",
        "PUERTO DEL MAR",
        "PUERTO PACHACUTEC",
        "ROSMERI SEGURA MORENO",
        "ROSMERY",
        "SANTA ROSA",
        "SEÑOR DE LOS MILAGROS II",
        "SECTOR 14 PROFAM",
        "SECTOR 6 NUEVA AMPLIACION",
        "TECHO PROPIO 1RA",
        "TECHO PROPIO 2DA",
        "TECHO PROPIO 3RA",
        "TECHO PROPIO 4TA",
        "TECHO PROPIO 5TA",
        "YOSHIYAMA",
        ""
    };
}
